/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz.Gastos;

import java.util.Observable;
import java.util.Observer;
import Interfaz.Errores.MontoBajo;
import Interfaz.Errores.Vacios;
import Modelo.Gasto;
import Modelo.Obra;
import Modelo.Rubro;
import Modelo.Sistema;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.math.BigDecimal;
import javax.swing.*;


/**
 *
 * @author varo1
 */
public class grObra extends javax.swing.JFrame implements Observer {
    private Sistema sistema;
    /**
     * Creates new form rgObra
     */
    public grObra(Sistema sistema1) {
        this.sistema = sistema1;
        this.sistema.addObserver(this);
        initComponents();
        if(this.obras!=null){
            obras.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent e) {
                    cargarImpagos();
                }
            });
        }        

        for (Obra c : this.sistema.getListaObra()) {
           this.obras.addItem(c.toString());
        }

        this.descrip.setText("Ej: Compra hecha en Pinturería Garzon. ");
        
        this.descrip.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (descrip.getText().equals("Ej: Compra hecha en Pinturería Garzon. ")) {
                    descrip.setText("");
                    descrip.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (descrip.getText().isEmpty()) {
                    descrip.setText("Ej: Compra hecha en Pinturería Garzon. ");
                    descrip.setForeground(new Color(153,153,153));
                }
            }
        });
    }
  
    private void cargarImpagos() {
        impagos.removeAllItems();
        String obraSeleccionada = (String) obras.getSelectedItem();
        if (obraSeleccionada != null) {
            for (Obra c : sistema.getListaObra()) {
                if (c.toString().equals(obraSeleccionada)) {
                    for (Rubro e : c.getRubros()) {
                        impagos.addItem(e.getNombre() + " -- " + e.getGastos());
                    }
                    SpinnerNumberModel setAnno = new SpinnerNumberModel(c.getAnno(), c.getAnno(), 2024, 1);
                    this.anno.setModel(setAnno);
                }
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        monto = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        SpinnerNumberModel setAnno = new SpinnerNumberModel(2010, 2010, 2024, 1);
        anno = new javax.swing.JSpinner();
        anno.setModel(setAnno);
        impagos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        obras = new javax.swing.JComboBox<>();
        SpinnerNumberModel setMes = new SpinnerNumberModel(1, 1, 12, 1);
        mes = new javax.swing.JSpinner();
        mes.setModel(setMes);
        registrar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descrip = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de gasto de rubro");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Obras");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Rubros");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Monto");

        monto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Mes");

        anno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        impagos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        impagos.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setText("Año");

        obras.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        obras.setForeground(new java.awt.Color(0, 0, 0));
        obras.setToolTipText("");

        mes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        registrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Descripción");

        descrip.setColumns(20);
        descrip.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        descrip.setForeground(new java.awt.Color(153, 153, 153));
        descrip.setRows(5);
        descrip.setText("Ej: Compra hecha en Pinturería Garzon. ");
        jScrollPane1.setViewportView(descrip);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(obras, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(impagos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14)
                            .addComponent(jLabel1)
                            .addComponent(jLabel13)
                            .addComponent(anno, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(monto)
                            .addComponent(mes))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(obras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(impagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(registrar)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        BigDecimal mont = BigDecimal.valueOf((Integer) this.monto.getValue());
        int r = this.impagos.getSelectedIndex();
        if(mont.compareTo(BigDecimal.ZERO)!=0){
            if(this.descrip.getText().equals("Ej: Compra hecha en Pinturería Garzon. ") || this.descrip.getText().isEmpty()){
                Vacios error = new Vacios();
                error.setVisible(true);    
            }else{
                int me = (Integer) this.mes.getValue();
                int ana = (Integer) this.anno.getValue();
                String des = this.descrip.getText();
                Gasto gas = new Gasto(mont, me, des, ana);
                Rubro ru = this.sistema.getObraPorNombre((String) obras.getSelectedItem()).getRubro(r);
                ru.agregarGastos(gas);
                this.dispose();
            }
        }else{
            if(this.descrip.getText().equals("Ej: Compra hecha en Pinturería Garzon. ") || this.descrip.getText().isEmpty()){
                Vacios error = new Vacios();
                error.setVisible(true);    
            }
            MontoBajo error = new MontoBajo();
            error.setVisible(true);    
        }
    }//GEN-LAST:event_registrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner anno;
    private javax.swing.JTextArea descrip;
    private javax.swing.JComboBox<String> impagos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner mes;
    private javax.swing.JSpinner monto;
    private javax.swing.JComboBox<String> obras;
    private javax.swing.JButton registrar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        if(arg.equals("obras")){
            for (Obra c : this.sistema.getListaObra()) {
                this.obras.addItem(c.toString());
            }
        }    
    }
}
