/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz.General;

import Interfaz.Gastos.*;
import Interfaz.ImportarYExportar.*;
import Interfaz.registros.*;
import Modelo.Serie_deserie;
import Modelo.Sistema;

/**
 *
 * @author varo1
 */
public class PeqOb extends javax.swing.JFrame {
    private Sistema sistema;
    private Serie_deserie seri;
    /**
     * Creates new form PeqOb
     */
    public PeqOb(Sistema sistema1, Serie_deserie seri1) {
        this.sistema = sistema1;
        this.seri = seri1;
        initComponents();
    }

    private PeqOb() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        Regis = new javax.swing.JMenu();
        RegisRubro = new javax.swing.JMenuItem();
        RegisCapa = new javax.swing.JMenuItem();
        RegisPropie = new javax.swing.JMenuItem();
        RegisObra = new javax.swing.JMenuItem();
        Gast = new javax.swing.JMenu();
        RegisGasto = new javax.swing.JMenuItem();
        PagoGasto = new javax.swing.JMenuItem();
        EstadoObr = new javax.swing.JMenuItem();
        ImpExp = new javax.swing.JMenu();
        Import = new javax.swing.JMenuItem();
        Export = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pantalla principal");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Regis.setText("Registros");
        Regis.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        RegisRubro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RegisRubro.setText("Registrar/Modificar rubro");
        RegisRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisRubroActionPerformed(evt);
            }
        });
        Regis.add(RegisRubro);

        RegisCapa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RegisCapa.setText("Registrar capataz");
        RegisCapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisCapaActionPerformed(evt);
            }
        });
        Regis.add(RegisCapa);

        RegisPropie.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RegisPropie.setText("Registro de propietario");
        RegisPropie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisPropieActionPerformed(evt);
            }
        });
        Regis.add(RegisPropie);

        RegisObra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RegisObra.setText("Registro de obra");
        RegisObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisObraActionPerformed(evt);
            }
        });
        Regis.add(RegisObra);

        menuBar.add(Regis);

        Gast.setText("Gastos");
        Gast.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        RegisGasto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RegisGasto.setText("Registro de gasto para obra");
        RegisGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisGastoActionPerformed(evt);
            }
        });
        Gast.add(RegisGasto);

        PagoGasto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PagoGasto.setText("Pago de gasto (Reintegro de gasto por parte del propietario)");
        PagoGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagoGastoActionPerformed(evt);
            }
        });
        Gast.add(PagoGasto);

        EstadoObr.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EstadoObr.setText("Estado de obra");
        EstadoObr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoObrActionPerformed(evt);
            }
        });
        Gast.add(EstadoObr);

        menuBar.add(Gast);

        ImpExp.setText("Importar y Exportar");
        ImpExp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        Import.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Import.setText("Importación de datos para obra nueva");
        Import.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportActionPerformed(evt);
            }
        });
        ImpExp.add(Import);

        Export.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Export.setText("Exportación de datos de Propietarios y Capataces");
        Export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportActionPerformed(evt);
            }
        });
        ImpExp.add(Export);

        menuBar.add(ImpExp);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportActionPerformed
        ImportarArch importar = new ImportarArch(this.sistema);
        importar.setVisible(true);
    }//GEN-LAST:event_ImportActionPerformed

    private void RegisRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisRubroActionPerformed
        rRubro root = new rRubro(this.sistema);
        root.setVisible(true);
    }//GEN-LAST:event_RegisRubroActionPerformed

    private void RegisCapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisCapaActionPerformed
        rCapataz root = new rCapataz(this.sistema);
        root.setVisible(true);
    }//GEN-LAST:event_RegisCapaActionPerformed

    private void RegisPropieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisPropieActionPerformed
        rPropietario root = new rPropietario(this.sistema);
        root.setVisible(true);
    }//GEN-LAST:event_RegisPropieActionPerformed

    private void RegisObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisObraActionPerformed
        rObra root = new rObra(this.sistema);
        root.setVisible(true);
    }//GEN-LAST:event_RegisObraActionPerformed

    private void EstadoObrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoObrActionPerformed
        gObra root = new gObra(this.sistema);
        root.setVisible(true);
    }//GEN-LAST:event_EstadoObrActionPerformed

    private void PagoGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagoGastoActionPerformed
        gPago root = new gPago(this.sistema);
        root.setVisible(true);
    }//GEN-LAST:event_PagoGastoActionPerformed

    private void RegisGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisGastoActionPerformed
        grObra root = new grObra(this.sistema);
        root.setVisible(true);
    }//GEN-LAST:event_RegisGastoActionPerformed

    private void ExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportActionPerformed
        Exportar root = new Exportar(this.sistema);
        root.setVisible(true);
    }//GEN-LAST:event_ExportActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.seri.serie(sistema);
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EstadoObr;
    private javax.swing.JMenuItem Export;
    private javax.swing.JMenu Gast;
    private javax.swing.JMenu ImpExp;
    private javax.swing.JMenuItem Import;
    private javax.swing.JMenuItem PagoGasto;
    private javax.swing.JMenu Regis;
    private javax.swing.JMenuItem RegisCapa;
    private javax.swing.JMenuItem RegisGasto;
    private javax.swing.JMenuItem RegisObra;
    private javax.swing.JMenuItem RegisPropie;
    private javax.swing.JMenuItem RegisRubro;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
