/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz.ImportarYExportar;

import Interfaz.Errores.eSoE;
import Modelo.ArchivoEscritura;
import Modelo.Capataz;
import Modelo.Propietario;
import Modelo.Sistema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author varo1
 */
public class Exportar extends javax.swing.JFrame {
    private Sistema sistema;
    ArrayList<Propietario> ow;
    ArrayList<Capataz> fo;

    public Exportar(Sistema sistema1) {
        this.sistema = sistema1;
        this.ow = this.sistema.getListaPropietario();
        this.fo = this.sistema.getListaCapataz();
        initComponents();
    }

    public void cedu(){
        this.sistema.ordenarCiP(ow);
        this.sistema.ordenarCiC(fo);
        ArchivoEscritura e = null;
        try {
            e = new ArchivoEscritura("Personas.txt", false);
        } catch (IOException ex) {
            eSoE eSoE = new eSoE();
            eSoE.setVisible(true);
            this.dispose();
        }
        e.grabarLinea("Propietarios");
        for(Propietario owner : ow){
            e.grabarLinea(owner.datos());
        }
        e.grabarLinea("Capataces");
        for(Capataz foreman : fo){
            e.grabarLinea(foreman.datos());
        }       
        e.cerrar();
        this.dispose();
    }
    
    public void nom(){
        this.sistema.ordenarNbP(ow);
        this.sistema.ordenarNbC(fo);
        ArchivoEscritura e = null;
        try {
            e = new ArchivoEscritura("Personas.txt", false);
        } catch (IOException ex) {
            eSoE eSoE = new eSoE();
            eSoE.setVisible(true);
            this.dispose();
        }
        e.grabarLinea("Propietarios");
        for(Propietario owner : ow){
            e.grabarLinea(owner.datos());
        }
        e.grabarLinea("Capataces");
        for(Capataz foreman : fo){
            e.grabarLinea(foreman.datos());
        }        
        e.cerrar();
        this.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JButton();
        cedu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nombre.setText("Por Nombre");
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        cedu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cedu.setText("Por Cedula");
        cedu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceduActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Elija cómo desear exportar los datos delos capataces y propietarios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cedu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(30, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cedu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ceduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceduActionPerformed
        cedu();
    }//GEN-LAST:event_ceduActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        nom();
    }//GEN-LAST:event_nombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cedu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nombre;
    // End of variables declaration//GEN-END:variables
}
